<?php

namespace Test\Andrebian\BrazilianHelpers\Filters;

use Andrebian\BrazilianHelpers\Filters\RemoveCnpjMaskFilter;
use PHPUnit\Framework\TestCase;

/**
 * Class RemoveCnpjMaskFilterTest
 * @package Test\Andrebian\BrazilianHelpers\Filters
 */
class RemoveCnpjMaskFilterTest extends TestCase
{

    public function getData()
    {
        // autogenerated CNPJs using this tool: https://www.4devs.com.br/gerador_de_cnpj
        return array(
            array('28735295000163', '28.735.295/0001-63'),
            array('41516274000115', '41.516.274/0001-15'),
            array('40069890000102', '40.069.890/0001-02'),
            array('00281205000192', '00.281.205/0001-92'),
        );
    }

    /**
     * @param $expected
     * @param $target
     * @dataProvider getData
     */
    public function testFilter($expected, $target)
    {
        $filter = new RemoveCnpjMaskFilter();
        $result = $filter->filter($target);

        $this->assertEquals($expected, $result);
    }
}
